server :
  port : 8090

api:
  coinGecko:
    domain: "api.coingecko.com"
    apiVersion: "/api/v3"
    endpoints:
      coinsList: "${api.coinGecko.apiVersion}/coins/list"
      coinsMarketData: "${api.coinGecko.apiVersion}/coins/markets"
      supportedVsCurrencies: "${api.coinGecko.apiVersion}/simple/supported_vs_currencies"
    apiKey: "CG-ZFJ6cHrCuDQm1xoiXe9dm2tG"
      