server:
  port: 8092

database:
  postgres: "db_product_data"

spring.datasource:
  #$driverClassName: "org.hibernate.dialect.PostgreSQLDialect"
  driverClassName: "org.postgresql.Driver"
  url: "jdbc:postgresql://localhost:5432/${database.postgres}"
  #url: "jdbc:postgresql://l92.168.1.46:5432/${database.postgres}"
  #url: "jdbc:postgresql://l72.21.0.2:5432/${database.postgres}"
  username: "postgres"
  password: "admin1234"

# spring.jpa.properties.hibernate.temp:
#   use_jdbc_metadata_defaults: false

# spring.datasource.hikari:
#   connectionInitSql: SET SEARCH_PATH TO ${database.postgres}

spring.jpa:
  show-sql: true
  hibernate.ddl-auto: update # update

api:
  bc-crypto-coingecko:
    domain: "localhost"
    port: "8090"
    apiVersion: "/crypto/coingecko/api/v1"
    endpoints:
      coinMarket: "/coins"
  bc-stock-finnhub:
    domain: "localhost"
    port: "8091"
    apiVersion: "/stock/finnhub/api/v1"
    endpoints:
      quote: "/quote"
      profile2: "/profile2"

spring.redis.host: 192.168.1.46
spring.redis.port: 6379