server:
  port: 8091

api:
  finnhub:
    domain: "finnhub.io"
    apiVersion: "/api/v1"
    endpoints:
      quote: "${api.finnhub.apiVersion}/quote"
      profile2: "${api.finnhub.apiVersion}/stock/profile2"
      stockSymbol: "${api.finnhub.apiVersion}/stock/symbol"
    apiKey: "cnhesthr01qhlsliu63gcnhesthr01qhlsliu640"

spring.redis.host: 192.168.1.46
spring.redis.port: 6379    