# String url = "https://jsonplaceholder.typicode.com/users";
api:
  jsonPlaceHolder:
    domain: "jsonplaceholder.typicode.com"
    endpoints:
      users: "/users"
      posts: "/posts"
      comments: "/comments"
      todos: "/todos"
      albums: "/albums"
      photos: "/photos"
server:
  port: 8080