FROM openjdk
LABEL maintainer="itsupport@gmail.com"
ADD target/bc-crypto-coingecko-0.0.1-SNAPSHOT.jar bc-crypto-coingecko-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar","bc-crypto-coingecko-0.0.1-SNAPSHOT.jar"]
EXPOSE 8090